"use client"
import { Geist, Geist_Mono, Anton, Bebas_Neue, Oswald, Bangers } from "next/font/google";
import type {Metadata} from "next";
import {AuthContextProvider} from "@/app/context/AuthContext";
import Navbar from "@/app/components/navbar";
import Link from "next/link";
import {MessageSquareMore} from "lucide-react";
import {usePathname} from "next/navigation";
import "@/app/globals.css";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const anton = Anton({
    variable: "--font-anton",
    weight: "400", // Anton only has 400 weight
    subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
    variable: "--font-bebas-neue",
    weight: "400", // Bebas Neue only has 400
    subsets: ["latin"],
});

const oswald = Oswald({
    variable: "--font-oswald",
    weight: ["400", "700"], // Oswald supports multiple weights
    subsets: ["latin"],
});

const bangers = Bangers({
    variable: "--font-bangers",
    weight: "400", // Bangers only has 400
    subsets: ["latin"],
});


// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const pathname = usePathname();
    const isChatPage = pathname === "/chat";
    const buttonText = isChatPage ? "ASK COMMUNITY" : "CHAT";
    const buttonLink = isChatPage ? "/community" : "/chat";
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable}  ${anton.variable} 
                    ${bebasNeue.variable} 
                    ${oswald.variable} 
                    ${bangers.variable} antialiased min-h-screen  bg-black`}
        >
        <AuthContextProvider>
            <Navbar/>
            {children}
            <div className="flex justify-end gap-4 items-center"  >
                <Link href={buttonLink}>
                    <div className="group fixed bg-green-800 p-2 w-16 h-16 flex items-center justify-center rounded-full bottom-5 right-5 hover:w-[15vw] transition-all duration-400 cursor-pointer" >
                        <MessageSquareMore color="white" size={32} className="transition-all duration-300 group-hover:mr-32"/>
                        <p className="absolute opacity-0 group-hover:opacity-100 transition-opacity duration-300 text-white text-center justify-end ml-8 text-sm whitespace-nowrap ">
                            {buttonText}
                        </p>
                    </div>
                </Link>
            </div>
        </AuthContextProvider>
        </body>
        </html>
    );
}

